import{db}from'./firebase-config.js';import{collection,getDocs,query,where,doc,getDoc,runTransaction,serverTimestamp}from'https://www.gstatic.com/firebasejs/12.19.0/firebase-firestore.js';import{requireAuth}from'./auth-guard.js';import{demoMovies}from'./demo-data.js';import{money,qs,pageParam,bookingRef,toast,friendlyError,initNav}from'./utils.js';initNav();
let user,movie,showtimes=[],selectedShowtime=null,selectedSeats=new Set();const snacks={popcornS:{name:'Small Popcorn',price:120},popcornL:{name:'Large Popcorn',price:180},drink:{name:'Soft Drink',price:100},nachos:{name:'Nachos',price:150},hotdog:{name:'Hotdog',price:140},combo:{name:'Combo Meal',price:250}};let snackQty={};
function calc(){const ticket=(selectedShowtime?.ticketPrice||movie?.ticketPrice||0)*selectedSeats.size;const food=Object.entries(snackQty).reduce((a,[k,q])=>a+(snacks[k]?.price||0)*q,0);const fee=selectedSeats.size?40:0;qs('#selectedSeats').textContent=[...selectedSeats].join(', ')||'None';qs('#ticketQty').textContent=selectedSeats.size;qs('#ticketSubtotal').textContent=money(ticket);qs('#snackSubtotal').textContent=money(food);qs('#fee').textContent=money(fee);qs('#total').textContent=money(ticket+food+fee);return{ticket,food,fee,total:ticket+food+fee}}
async function getMovie(){const id=pageParam('movie');try{const s=await getDoc(doc(db,'movies',id));if(s.exists())return{id:s.id,...s.data()}}catch{}return demoMovies.find(m=>m.id===id)||demoMovies[0]}
async function loadShowtimes(){try{const snap=await getDocs(query(collection(db,'showtimes'),where('movieId','==',movie.id),where('status','==','active')));showtimes=snap.docs.map(d=>({id:d.id,...d.data()}))}catch{showtimes=[]}const sel=qs('#showtime');sel.innerHTML='<option value="">Select a showtime</option>'+showtimes.map(s=>`<option value="${s.id}">${s.date} · ${s.time} · ${s.cinemaLocation} · ${s.cinemaRoom}</option>`).join('')}
async function occupied(){if(!selectedShowtime)return new Set();try{const s=await getDocs(query(collection(db,'seatLocks'),where('showtimeId','==',selectedShowtime.id)));return new Set(s.docs.map(d=>d.data().seat))}catch{return new Set()}}
async function drawSeats(){selectedSeats.clear();const occ=await occupied();const box=qs('#seatGrid');box.innerHTML='';for(const row of 'ABCDEFGH'){const r=document.createElement('div');r.className='seat-row';for(let n=1;n<=10;n++){const id=row+n,b=document.createElement('button');b.type='button';b.className='seat'+(row>='G'?' premium':'')+(occ.has(id)?' occupied':'');b.textContent=id;b.disabled=occ.has(id);b.onclick=()=>{selectedSeats.has(id)?selectedSeats.delete(id):selectedSeats.add(id);b.classList.toggle('selected');calc()};r.append(b)}box.append(r)}calc()}
function renderSnacks(){qs('#snacks').innerHTML=Object.entries(snacks).map(([k,s])=>`<div class="summary-row"><span>${s.name} — ${money(s.price)}</span><span><button class="btn btn-secondary" data-snack="${k}" data-delta="-1">−</button> <b id="qty-${k}">0</b> <button class="btn btn-secondary" data-snack="${k}" data-delta="1">+</button></span></div>`).join('')}
qs('#snacks')?.addEventListener('click',e=>{const b=e.target.closest('[data-snack]');if(!b)return;const k=b.dataset.snack;snackQty[k]=Math.max(0,(snackQty[k]||0)+Number(b.dataset.delta));qs('#qty-'+k).textContent=snackQty[k];calc()});
qs('#showtime')?.addEventListener('change',async e=>{selectedShowtime=showtimes.find(s=>s.id===e.target.value)||null;await drawSeats()});
qs('#continuePayment')?.addEventListener('click',()=>{if(!selectedShowtime)return toast('Please select a showtime.','error');if(!selectedSeats.size)return toast('Please select at least one seat.','error');sessionStorage.setItem('cineversePending',JSON.stringify({movie,showtime:selectedShowtime,seats:[...selectedSeats],snackQty,totals:calc()}));location.href='payment.html'});
(async()=>{user=await requireAuth();movie=await getMovie();qs('#bookingMovie').textContent=movie.title;qs('#bookingPoster').src=movie.posterUrl;renderSnacks();await loadShowtimes();await drawSeats()})();
