import{db}from'../firebase-config.js';import{collection,getDocs,addDoc,doc,getDoc,updateDoc,deleteDoc,serverTimestamp}from'https://www.gstatic.com/firebasejs/12.19.0/firebase-firestore.js';import{adminInit}from'./common.js';import{money,qs,toast,friendlyError,setButtonLoading}from'../utils.js';let rows=[],editing=null;
function readForm(){const genres=qs('#genres').value.split(',').map(x=>x.trim()).filter(Boolean);return{title:qs('#title').value.trim(),posterUrl:qs('#posterUrl').value.trim(),backdropUrl:qs('#backdropUrl').value.trim(),trailerUrl:qs('#trailerUrl').value.trim(),genres,runtime:Number(qs('#runtime').value),ageRating:qs('#ageRating').value.trim(),releaseDate:qs('#releaseDate').value,director:qs('#director').value.trim(),cast:qs('#cast').value.trim(),synopsis:qs('#synopsis').value.trim(),ticketPrice:Number(qs('#ticketPrice').value),status:qs('#status').value,featured:qs('#featured').checked}}
function valid(m){if(!m.title)return 'Movie title is required.';if(!(m.runtime>0))return 'Runtime must be greater than zero.';if(!(m.ticketPrice>0))return 'Ticket price must be greater than ₱0.';if(!m.releaseDate)return 'Release date is required.';if(!m.synopsis)return 'Synopsis is required.';if(!m.status)return 'Status is required.';return ''}
async function load(){const s=await getDocs(collection(db,'movies'));rows=s.docs.map(d=>({id:d.id,...d.data()}));render()}
function render(){const q=(qs('#search')?.value||'').toLowerCase(),st=qs('#filterStatus')?.value||'';const list=rows.filter(m=>m.title.toLowerCase().includes(q)&&(!st||m.status===st));qs('#movieRows').innerHTML=list.length?list.map(m=>`<tr><td>${m.title}</td><td>${(m.genres||[]).join(', ')}</td><td>${m.status}</td><td>${money(m.ticketPrice)}</td><td><button class="btn btn-secondary" data-edit="${m.id}">Edit</button> <button class="btn btn-danger" data-delete="${m.id}">Delete</button></td></tr>`).join(''):'<tr><td colspan="5">No movie records found. Add your first movie.</td></tr>'}
function fill(m){editing=m.id;qs('#title').value=m.title||'';qs('#posterUrl').value=m.posterUrl||'';qs('#backdropUrl').value=m.backdropUrl||'';qs('#trailerUrl').value=m.trailerUrl||'';qs('#genres').value=(m.genres||[]).join(', ');qs('#runtime').value=m.runtime||'';qs('#ageRating').value=m.ageRating||'';qs('#releaseDate').value=m.releaseDate||'';qs('#director').value=m.director||'';qs('#cast').value=m.cast||'';qs('#synopsis').value=m.synopsis||'';qs('#ticketPrice').value=m.ticketPrice||'';qs('#status').value=m.status||'now-showing';qs('#featured').checked=!!m.featured;qs('#formTitle').textContent='Edit Movie';qs('#cancelEdit').classList.remove('hidden');scrollTo({top:0,behavior:'smooth'})}
function reset(){editing=null;qs('#movieForm').reset();qs('#formTitle').textContent='Add Movie';qs('#cancelEdit').classList.add('hidden')}
qs('#movieForm')?.addEventListener('submit',async e=>{e.preventDefault();const btn=qs('#saveMovie'),m=readForm(),err=valid(m);if(err)return toast(err,'error');try{setButtonLoading(btn,true,'Saving movie...');if(editing){await updateDoc(doc(db,'movies',editing),{...m,updatedAt:serverTimestamp()});toast('Movie updated successfully.')}else{await addDoc(collection(db,'movies'),{...m,createdAt:serverTimestamp(),updatedAt:serverTimestamp()});toast('Movie added successfully.')}reset();await load()}catch(e){toast(friendlyError(e),'error')}finally{setButtonLoading(btn,false)}});
qs('#movieRows')?.addEventListener('click',async e=>{const edit=e.target.closest('[data-edit]'),del=e.target.closest('[data-delete]');if(edit){fill(rows.find(x=>x.id===edit.dataset.edit));return}if(del){const m=rows.find(x=>x.id===del.dataset.delete);if(confirm(`Delete '${m.title}'?\n\nThis action cannot be undone.`)){try{await deleteDoc(doc(db,'movies',m.id));toast('Movie deleted successfully.');await load()}catch(err){toast(friendlyError(err),'error')}}}});qs('#search')?.addEventListener('input',render);qs('#filterStatus')?.addEventListener('change',render);qs('#cancelEdit')?.addEventListener('click',reset);await adminInit();load();
